version: 2

base_image: &base_image
  image: circleci/node:8.3.0

job_common: &job_common
  docker:
    - <<: *base_image
  working_directory: ~/sandbox/code

attach: &attach
  attach_workspace:
    at: ~/sandbox

store_artifacts: &store_artifacts
  store_artifacts:
    path: ~/sandbox/code/coverage
    destination: /

store_test_results: &store_test_results
  store_test_results:
    path: ~/sandbox/code/coverage

jobs:
  build:
    <<: *job_common
    steps:
      - checkout:
          path: ~/sandbox/code
      - restore_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/sandbox/code/node_modules
      - run: yarn run build
      - persist_to_workspace:
          root: ~/sandbox
          paths: code

  test:
    <<: *job_common
    steps:
      - checkout
      - <<: *attach
      - run: yarn run test:coverage
      - <<: *store_artifacts
      - <<: *store_test_results

  release:
    <<: *job_common
    steps:
      - checkout
      - <<: *attach
      - run: yarn config set registry https://registry.npmjs.org/
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: git config --global user.email "donvoy@convoy.com"
      - run: git config --global user.name "Don Voy"
      - run: yarn run release
      - <<: *store_artifacts

workflows:
  version: 2
  build-test-release:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          requires:
            - test
          filters:
            branches:
              only: master
